drop table pc_fivetran_db.public.customers_raw;
drop table pc_fivetran_db.public.inventorylog_raw;
drop table pc_fivetran_db.public.payments_raw;
drop table pc_fivetran_db.public.org;
drop table pc_fivetran_db.public.location_type_desc;
drop table pc_fivetran_db.public.inventory_raw;
drop table pc_fivetran_db.public.inventorytypes_raw;
drop table pc_fivetran_db.public.inventoryrooms_raw;
drop table pc_fivetran_db.public.productcategories_raw;
drop table pc_fivetran_db.public.productslog_raw;
drop table pc_fivetran_db.public.products_raw;
drop table pc_fivetran_db.public.rooms_raw;
drop table pc_fivetran_db.public.sales_raw;
drop table pc_fivetran_db.public.taxcategories_raw;
drop table pc_fivetran_db.public.tickets_raw;
drop table pc_fivetran_db.public.vendors_raw;

create table pc_fivetran_db.public.customers_raw as select * from pc_fivetran_db.postgres_cann_replication_public.customers_raw;
create table pc_fivetran_db.public.inventorylog_raw as select * from pc_fivetran_db.postgres_cann_replication_public.inventorylog_raw;
create table pc_fivetran_db.public.payments_raw as select * from pc_fivetran_db.postgres_cann_replication_public.payments_raw;
create table pc_fivetran_db.public.org as select * from pc_fivetran_db.postgres_cann_replication_public.org;
create table pc_fivetran_db.public.location_type_desc as select * from pc_fivetran_db.postgres_cann_replication_public.location_type_desc;
create table pc_fivetran_db.public.locations_raw as select * from pc_fivetran_db.postgres_cann_replication_public.locations_raw;
create table pc_fivetran_db.public.inventory_raw as select * from pc_fivetran_db.postgres_cann_replication_public.inventory_raw;
create table pc_fivetran_db.public.inventorytypes_raw as select * from pc_fivetran_db.postgres_cann_replication_public.inventorytypes_raw;
create table pc_fivetran_db.public.inventoryrooms_raw as select * from pc_fivetran_db.postgres_cann_replication_public.inventoryrooms_raw;
create table pc_fivetran_db.public.productcategories_raw as select * from pc_fivetran_db.postgres_cann_replication_public.productcategories_raw;
create table pc_fivetran_db.public.productslog_raw as select * from pc_fivetran_db.postgres_cann_replication_public.productslog_raw;
create table pc_fivetran_db.public.products_raw as select * from pc_fivetran_db.postgres_cann_replication_public.products_raw;
create table pc_fivetran_db.public.rooms_raw as select * from pc_fivetran_db.postgres_cann_replication_public.rooms_raw;
create table pc_fivetran_db.public.sales_raw as select * from pc_fivetran_db.postgres_cann_replication_public.sales_raw;
create table pc_fivetran_db.public.taxcategories_raw as select * from pc_fivetran_db.postgres_cann_replication_public.taxcategories_raw;
create table pc_fivetran_db.public.tickets_raw as select * from pc_fivetran_db.postgres_cann_replication_public.tickets_raw;
create table pc_fivetran_db.public.vendors_raw as select * from pc_fivetran_db.postgres_cann_replication_public.vendors_raw;